### ISSUE TITLE
Failing Tests That Need to Be Resolved

### ISSUE THREAD

**Issue by mzagaja** [codeforboston/cambridge_energy_app#161]
```
Failures:

  1) BillsController GET #edit should respond with 200
     Failure/Error: it { is_expected.to respond_with :ok }
       Expected response to be a 200, but was 302
     # ./spec/controllers/bills_controller_spec.rb:36:in `block (3 levels) in <top (required)>'

  2) BillsController GET #edit should render template matcher "edit"
     Failure/Error: it { is_expected.to render_template :edit }
       expecting <"edit"> but was a redirect to <http://test.host/users/me>
     # ./spec/controllers/bills_controller_spec.rb:37:in `block (3 levels) in <top (required)>'

  3) BillsController PATCH #update redirects to the bill show page
     Failure/Error: expect(response).to redirect_to bill_path(@bill)

       Expected response to be a redirect to <http://test.host/bills/11> but was a redirect to <http://test.host/users/me>.
       Expected "http://test.host/bills/11" to be === "http://test.host/users/me".
     # ./spec/controllers/bills_controller_spec.rb:57:in `block (3 levels) in <top (required)>'

  4) BillsController DELETE #destroy destroys a bill
     Failure/Error: expect{ delete(:destroy, id: @bill.id) }.to change{ Bill.count }.by(-1)
       expected result to have changed by -1, but was changed by 0
     # ./spec/controllers/bills_controller_spec.rb:63:in `block (3 levels) in <top (required)>'

  5) InvitationsController DELETE #destroy inviter cancels invitation is successful
     Failure/Error:
       expect{ delete(:destroy, id: @invitation.id) }
         .to change{ Invitation.count }.by(-1)

       expected result to have changed by -1, but was changed by 0
     # ./spec/controllers/invitations_controller_spec.rb:82:in `block (4 levels) in <top (required)>'

  6) TeamsController PATCH #update when user is signed in is successful
     Failure/Error: expect(response).to redirect_to team_path(@team)

       Expected response to be a redirect to <http://test.host/teams/21> but was a redirect to <http://test.host/users/me.39>.
       Expected "http://test.host/teams/21" to be === "http://test.host/users/me.39".
     # ./spec/controllers/teams_controller_spec.rb:83:in `block (4 levels) in <top (required)>'

  7) TeamsController GET #leave team has more than one member does not destroy team
     Failure/Error: expect(response).to redirect_to users_me_path

       Expected response to be a redirect to <http://test.host/users/me> but was a redirect to <http://test.host/users/me.40>.
       Expected "http://test.host/users/me" to be === "http://test.host/users/me.40".
     # ./spec/controllers/teams_controller_spec.rb:111:in `block (4 levels) in <top (required)>'

Finished in 2.58 seconds (files took 5.76 seconds to load)
60 examples, 7 failures, 3 pending
```
- [x] rspec ./spec/controllers/bills_controller_spec.rb:36 # BillsController GET #edit should respond with 200
- [x] rspec ./spec/controllers/bills_controller_spec.rb:37 # BillsController GET #edit should render template matcher "edit"
- [x] rspec ./spec/controllers/bills_controller_spec.rb:53 # BillsController PATCH #update redirects to the bill show page
- [x] rspec ./spec/controllers/bills_controller_spec.rb:62 # BillsController DELETE #destroy destroys a bill
- [x] rspec ./spec/controllers/invitations_controller_spec.rb:78 # InvitationsController DELETE #destroy inviter cancels invitation is successful
- [x] rspec ./spec/controllers/teams_controller_spec.rb:76 # TeamsController PATCH #update when user is signed in is successful
- [x] rspec ./spec/controllers/teams_controller_spec.rb:106 # TeamsController GET #leave team has more than one member does not destroy team

**Comment by mzagaja** [comment]
Hey @veddster were you working on these?

**Comment by matthewvedder** [comment]
Yes. As you suspected, the tests started failing after commit #d73c9d4 -m "Simple action authorization." The authorize_user methods in each controller are causing the tests to fail.

**Comment by mzagaja** [comment]
```
Failures:

  1) BillsController GET #comparison 
     Failure/Error: most_recent_bill_id = Bill.joins(:unit).where('units.id' => current_or_guest_user.unit.id).order(:created_at).last.id || 0

     NoMethodError:
       undefined method `id' for nil:NilClass
     # ./app/controllers/bills_controller.rb:28:in `comparison'
     # /Users/mzagaja/.rvm/gems/ruby-2.2.4@cambridge_energy_challenge/gems/devise-4.0.0/lib/devise/test_helpers.rb:19:in `block in process'
     # /Users/mzagaja/.rvm/gems/ruby-2.2.4@cambridge_energy_challenge/gems/devise-4.0.0/lib/devise/test_helpers.rb:75:in `catch'
     # /Users/mzagaja/.rvm/gems/ruby-2.2.4@cambridge_energy_challenge/gems/devise-4.0.0/lib/devise/test_helpers.rb:75:in `_catch_warden'
     # /Users/mzagaja/.rvm/gems/ruby-2.2.4@cambridge_energy_challenge/gems/devise-4.0.0/lib/devise/test_helpers.rb:19:in `process'
     # ./spec/controllers/bills_controller_spec.rb:44:in `block (3 levels) in <top (required)>'

  2) InvitationsController GET #join reciever is already on a team reciever is not yet on a team adds user to invitation attached to team
     Failure/Error: expect(response).to redirect_to invitation.sender

       Expected response to be a redirect to <http://test.host/teams/45> but was a redirect to <http://test.host/users/me>.
       Expected "http://test.host/teams/45" to be === "http://test.host/users/me".
     # ./spec/controllers/invitations_controller_spec.rb:108:in `block (5 levels) in <top (required)>'

  3) user can add a new bill user successfully adds new bill
     Failure/Error: expect(page).to have_content "You can save money on your energy bill"
       expected to find text "You can save money on your energy bill" in "EnerSave Sign Up Log In Back How does my energy bill compare to my neighbors in Cambridge? Sign up to learn how to save money on your energy bill: Email Password Password confirmation"
     # ./spec/features/user_can_create_new_bill_spec.rb:11:in `block (2 levels) in <top (required)>'

Finished in 4.19 seconds (files took 6.1 seconds to load)
79 examples, 3 failures

Failed examples:

rspec ./spec/controllers/bills_controller_spec.rb:46 # BillsController GET #comparison 
rspec ./spec/controllers/invitations_controller_spec.rb:104 # InvitationsController GET #join reciever is already on a team reciever is not yet on a team adds user to invitation attached to team
rspec ./spec/features/user_can_create_new_bill_spec.rb:4 # user can add a new bill user successfully adds new bill
```

**Comment by mzagaja** [comment]
#170 broke rspec ./spec/features/user_can_create_new_bill_spec.rb:43 # user can add a new bill user enters invalid bill information - less than case.
