### ISSUE TITLE
PR #165 Broke Two Unit controller tests

### ISSUE THREAD

**Issue by mzagaja** [codeforboston/cambridge_energy_app#179]
```
Failures:
  1) UnitsController POST #create is not successful due to failing validations
     Failure/Error: expect(response).to render_template :new
       expecting <"new"> but was a redirect to <http://test.host/units/26>
     # ./spec/controllers/units_controller_spec.rb:91:in `block (3 levels) in <top (required)>'
  2) UnitsController POST #create new unit is created with new address is successful
     Failure/Error:
       expect(&post).to change{ Unit.count }
         .and change{ UserBuilding.count }.by(1)

       expected result to have changed by 1, but was changed by 0
     # ./spec/controllers/units_controller_spec.rb:73:in `block (4 levels) in <top (required)>'
Finished in 3.05 seconds (files took 6.46 seconds to load)
64 examples, 2 failures
Failed examples:
rspec ./spec/controllers/units_controller_spec.rb:79 # UnitsController POST #create is not successful due to failing validations
rspec ./spec/controllers/units_controller_spec.rb:63 # UnitsController POST #create new unit is created with new address is successful
```

Snuck past me because I forgot Travis was not properly enabled on that branch.

**Comment by kvotolato3** [comment]
Just realized we have an autocomplete feature on addresses that somehow slipped by me. I will need to make a few more changes before this pull request can be merged.
