### ISSUE TITLE
Heroku Build is Crashing

### ISSUE THREAD

**Issue by mzagaja** [codeforboston/cambridge_energy_app#40]
From the log:

```
2016-01-10T21:19:48.686918+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/server.rb:272:in `start'
2016-01-10T21:19:48.686919+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/commands/server.rb:80:in `start'
2016-01-10T21:19:48.686922+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:80:in `block in server'
2016-01-10T21:19:48.686924+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:75:in `server'
2016-01-10T21:19:48.686927+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
2016-01-10T21:19:48.686944+00:00 app[web.1]:    from bin/rails:9:in `<main>'
2016-01-10T21:19:49.694718+00:00 heroku[web.1]: State changed from starting to crashed
```

I tried heroku run rake db:reset in case it was a DB issue, along with upping the version of ruby to match my development version with no luck. If someone wants to dig into this ping me and I'll add you as a collaborator to the Heroku dyno.

**Comment by mzagaja** [comment]
Ok apparently I just couldn't figure out how to find useful Heroku logs but it is now fixed. I don't really understand why this syntax change was necessary but I'm happy it works.
